wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 50
dataset:
  desc: null
  value: Titanic
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713530924.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
