wandb_version: 1

n_seeds:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
k_folds:
  desc: null
  value: 5
val_size:
  desc: null
  value: 0.25
min_single_eval_pos:
  desc: null
  value: 100
epochs:
  desc: null
  value: 250
learning_rate:
  desc: null
  value: 1.0e-05
num_workers:
  desc: null
  value: 0
dataset_ids:
  desc: null
  value:
  - 168746
log_wandb:
  desc: null
  value: true
name:
  desc: null
  value: Finetune-TabPFN
models:
  desc: null
  value:
  - sklearn.ensemble._forest.RandomForestClassifier
  - sklearn.tree._classes.DecisionTreeClassifier
  - tabpfn.scripts.transformer_prediction_interface.TabPFNClassifier
'device ':
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714025244.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
